# Site settings
title: Sanghyun Han
email: shhan@gatech.edu
description: >
 Sam Nunn School of International Affairs
 Georgia Institute of Technology
 Atlanta, GA 30318
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sanghyun-ir.github.io" # the base hostname & protocol for your site
github_username:  sanghyun-ir
encoding: UTF-8
# Build settings
markdown: kramdown
